config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/home',    to: 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'

  # get '/signup',  to: 'users#new'
  # post '/signup',  to: 'users#create'

  # post '/login', to: 'users/sessions#create'
  # get '/login', to: 'users/sessions#new'
  # delete '/logout', to: 'sessions#destroy'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  },
  path_names: { sign_in: 'login', sign_out: 'logout'}

  authenticated :user do
    root "users#show"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :create, :new] do
    root "users#show"
  end

  resources :polls do
    root "polls#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user

  # has_many :answers

  validates :question, presence: true
  validates :answers, presence: true

  # accepts_nested_attributes_for :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :polls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
  protect_from_forgery with: :exception

  include SessionsHelper

  def hello
    render html: "hello world"
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def index
    @polls = Poll.all
  end

  def new
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def create
    build_user
    poll = Poll.new(poll_params)
    if poll.save
      flash[:success] = "Poll has been created"
      redirect_to :back
    else
      flash[:warning] = "could not create because " + poll.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def update
    poll = Poll.find(params[:id])
    if poll.update(poll_params)
      flash[:success] = "VOTED"
    else
      flash[:warning] = "could not create because " + poll.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def poll_params
    params[:answers] = params[:answers].map{|k, v| v}
    params.permit(:question, :user_id, :answers => [:text, :count])
  end

  def build_user
    params[:user_id] = current_user.id
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end

  def help
  end

  def about
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    build_resource({})
    respond_with self.resource
  end

  def create
    super
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  # def create
  #   user = User.find_by(email: params[:session][:email].downcase)
  #   if user && user.authenticate(params[:session][:password])
  #     log_in user
  #     remember user
  #     redirect_to user
  #   else
  #     # Create an error message.
  #     flash.now[:danger] = 'Invalid email/password combination'
  #     render 'new'
  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash.now[:success] = "Successful signup"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # def log_in(user)
  #   session[:user_id] = user.id
  # end
  #
  # def current_user
  #   if (user_id = session[:user_id])
  #     @current_user ||= User.find_by(id: user_id)
  #   elsif (user_id = cookies.signed[:user_id])
  #     user = User.find_by(id: user_id)
  #     if user && user.authenticated?(cookies[:remember_token])
  #       log_in user
  #       @current_user = user
  #     end
  #   end
  # end
  #
  # def logged_in?
  #   !current_user.nil?
  # end
  #
  # def log_out
  #   session.delete(:user_id)
  #   @current_user = nil
  # end
  #
  # def remember(user)
  #   user.remember
  #   cookies.permanent.signed[:user_id] = user.id
  #   cookies.permanent[:remember_token] = user.remember_token
  # end
  #
  # def forget(user)
  #   user.forget
  #   cookies.delete[:user_id]
  #   cookies.delete[:remember_token]
  # end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/header'
    .container
      - flash.each do |message_type, message|
        div class=("alert alert-#{message_type}")
          = message
      = yield
    = render 'shared/footer'

app/views/polls/index.html.slim
= provide(:title, "List of Polls")

.list-container
  h3.center.col-md-12
    | List of available polls
  table.table.table-striped
    thead
      tr
        th.col-md-2
          span.grey #
        th.col-md-4
          span Owner
        th.col-md-6
          span Question
    tbody
      - @polls.each do |poll|
        tr.table-row.pointer.poll-click data-href="#{poll_path(poll)}"
          td.grey =poll.id
          td.blue =poll.user.email
          td =poll.question

app/views/polls/new.html.slim
= provide(:title, "Log in")
.form-container.jumbotron
  h3.center.col-md-12
    | Create Poll
  .row
    .col-md-10.col-md-offset-1
      = react_component('FormCreate')
      /= form_for(:session, url: login_path) do |f|
      /  = f.label :email
      /  = f.email_field :email, class: 'form-control'
      /  = f.label :password
      /  = f.password_field :password, class: "form-control"
      /  = f.submit "Log in", class: "btn btn-primary"
      /p
      /  | New user?
      /  = link_to " Sign up now!", signup_path

app/views/polls/show.html.slim
= provide(:title, "#{@poll.question}")

.poll-container
  h3.center.col-md-12.question
    = @poll.question
  div.col-md-12.pull-left.answers
    = react_component('Vote', {poll: @poll, authenticity_token: form_authenticity_token})

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains #{pluralize(@user.errors.count, "error")}.
    ul
      - @user.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_footer.html.slim
footer.footer
  small
    | Codyssey Poll &copy; Codyssey web
  nav
    ul
      li= link_to "About",   '#'
      li= link_to "Contact", '#'

app/views/shared/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .header-container
    = link_to "Codyssey Poll", "#", id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li= link_to "Home", home_path
        li= link_to "Help", help_path
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | Account
              b.caret
            ul.dropdown-menu
              li = link_to "Profile", current_user
              li.divider
              li = link_to "Logout", destroy_user_session_path , method: "delete"
        - else
          li= link_to "Log in", new_user_session_path

app/views/static_pages/about.html.slim
= provide(:title, "about")
h1 About
p this is about page

app/views/static_pages/help.html.slim
= provide(:title, "help")
title
    = yield(:title)
      | | tutorial
      h1 Help
      p This is help page

app/views/static_pages/home.html.slim
.center.jumbotron.home-container
  h1
    | Poll this webpage
  h2
    | lorem ipsum hello world is there somebody
    a href="#"  Link another
    |  Poll Me
  div.row
    span.col-md-6
      = link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary pull-right"
    span.col-md-6
      = link_to "View Available Polls", polls_path, class: "btn btn-lg btn-primary pull-left"

app/views/users/show.html.slim
= provide(:title, "User Profile")
.row.user-container
  aside.col-md-4
    section.user_info
      h1.center
        = current_user.email
      /span.center
      /  = @user.email
  div.col-md-8.poll-options
    div.button-holder
      = link_to "View Available Polls", "#", class: "btn btn-lg btn-primary pull-left button-medium"
    div.button-holder
      = link_to "Create Polls", new_poll_path, class: "btn btn-lg btn-primary pull-left button-medium"